defmodule Remembly.Repo.Migrations.RemoveUrlAddMessageContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      remove :url
      add :message_content, :text, null: false
    end
  end

  def down do
    alter table(:messages) do
      remove :message_content
      add :url, :text, null: false
    end
  end
end
