defmodule Remembly.Repo.Migrations.ChangeMessageContentToContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:messages), :message_content, to: :content

    alter table(:messages) do
      modify :content, :text
    end
  end

  def down do
    alter table(:messages) do
      modify :message_content, :text
    end

    rename table(:messages), :content, to: :message_content
  end
end
