defmodule Remembly.Repo.Migrations.AddCategoryResourceAndRelationshipToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :reference_id, :text, null: false
      add :category_id, :uuid
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "messages_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:messages, [:reference_id], name: "messages_message_reference_id_index")

    alter table(:categories) do
      add :label, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:categories) do
      remove :updated_at
      remove :inserted_at
      remove :label
    end

    drop_if_exists unique_index(:messages, [:reference_id],
                     name: "messages_message_reference_id_index"
                   )

    drop constraint(:messages, "messages_category_id_fkey")

    alter table(:messages) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    alter table(:messages) do
      remove :category_id
      remove :reference_id
    end
  end
end
