defmodule Remembly.Repo.Migrations.RemoveMessageContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      remove :content
    end
  end

  def down do
    alter table(:messages) do
      add :content, :text, null: false
    end
  end
end
